import { ArrowLeft } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'

export function TermsPage() {
  const { t } = useTranslation()

  return (
    <div className="min-h-screen px-4 py-12 bg-background text-foreground">
      <article className="app-shell max-w-3xl prose prose-neutral dark:prose-invert">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-sm font-bold uppercase tracking-widest text-muted-foreground hover:text-foreground transition-colors no-underline mb-8"
        >
          <ArrowLeft className="w-4 h-4" />
          {t('legal.backToHome', 'Back to Home')}
        </Link>

        <h1 className="text-4xl font-black uppercase tracking-tight border-b-4 border-border pb-4 mb-8">
          {t('legal.termsTitle', 'Terms of Service')}
        </h1>

        <p className="text-sm text-muted-foreground mb-8">
          {t('legal.lastUpdated', 'Last updated')}: 2026-03-22
        </p>

        <h2>{t('legal.terms.acceptanceTitle', '1. Acceptance of Terms')}</h2>
        <p>
          {t(
            'legal.terms.acceptance',
            'By accessing or using IdeaGo ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.',
          )}
        </p>

        <h2>{t('legal.terms.descriptionTitle', '2. Description of Service')}</h2>
        <p>
          {t(
            'legal.terms.description',
            'IdeaGo is an AI-powered competitor research platform. We aggregate publicly available information and generate analytical reports. Reports are generated by AI and may contain inaccuracies.',
          )}
        </p>

        <h2>{t('legal.terms.accountsTitle', '3. Anonymous Use')}</h2>
        <p>
          {t(
            'legal.terms.accounts',
            'The personal deployment does not require user accounts. You are responsible for controlling access to your own deployment and using the Service lawfully.',
          )}
        </p>

        <h2>{t('legal.terms.subscriptionTitle', '4. Providers & Costs')}</h2>
        <p>
          {t(
            'legal.terms.subscription',
            'The personal deployment does not include built-in billing or account management. If you configure external model or retrieval providers, your use of those providers is governed by their own terms.',
          )}
        </p>

        <h2>{t('legal.terms.ipTitle', '5. Intellectual Property')}</h2>
        <p>
          {t(
            'legal.terms.ip',
            'Reports generated for you are yours to use. The Service, its code, and branding remain the property of IdeaGo.',
          )}
        </p>

        <h2>{t('legal.terms.disclaimerTitle', '6. Disclaimer')}</h2>
        <p>
          {t(
            'legal.terms.disclaimer',
            'The Service is provided "as is". We do not guarantee the accuracy, completeness, or timeliness of any information provided. Use reports at your own risk.',
          )}
        </p>

        <h2>{t('legal.terms.limitationTitle', '7. Limitation of Liability')}</h2>
        <p>
          {t(
            'legal.terms.limitation',
            'To the maximum extent permitted by law, IdeaGo shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.',
          )}
        </p>

        <h2>{t('legal.terms.changesTitle', '8. Changes to Terms')}</h2>
        <p>
          {t(
            'legal.terms.changes',
            'We may update these terms from time to time. Continued use of the Service constitutes acceptance of the updated terms.',
          )}
        </p>

        <h2>{t('legal.terms.contactTitle', '9. Contact')}</h2>
        <p>
          {t(
            'legal.terms.contact',
            'For questions about these terms, please contact us through the channels listed on our website.',
          )}
        </p>
      </article>
    </div>
  )
}
