import { ArrowLeft, ArrowRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { useDocumentTitle } from '@/hooks/useDocumentTitle'

interface LegalSection {
  id: string
  title: string
  body: string
}

export function TermsPage() {
  const { t, i18n } = useTranslation()
  const isChinese = (i18n.resolvedLanguage ?? i18n.language ?? 'en').startsWith('zh')

  useDocumentTitle(`${t('legal.termsTitle', 'Terms of Service')} | IdeaGo`)

  const pageCopy = isChinese
    ? {
        intro: '本页说明使用 IdeaGo 服务时适用的基本规则、责任边界、计费原则，以及我们与用户之间的权利义务。',
        panelTitle: '阅读重点',
        panelBody: '如果你想快速把握关键内容，建议优先查看服务说明、免责声明、责任限制和条款变更这几部分。',
        navTitle: '章节导航',
        summaryLabel: '适用范围',
        summaryValue: '账户使用、报告内容、订阅计费、知识产权与责任边界',
        noteTitle: '条款更新说明',
        noteBody: '当服务规则发生重要变化时，我们会在页面或应用内提示。继续使用服务通常表示你接受更新后的条款。',
      }
    : {
        intro:
          'This page explains the rules that apply when using IdeaGo, including service boundaries, billing expectations, ownership, and responsibility.',
        panelTitle: 'Read this first',
        panelBody:
          'If you want the essentials quickly, start with Description of Service, Disclaimer, Limitation of Liability, and Changes to Terms.',
        navTitle: 'Section map',
        summaryLabel: 'Coverage',
        summaryValue: 'Accounts, generated reports, subscriptions, intellectual property, and liability boundaries',
        noteTitle: 'Terms update notice',
        noteBody:
          'When these terms change in a material way, we will highlight the update on the page or in-app. Continued use generally means you accept the revised terms.',
      }

  const sections: LegalSection[] = [
    {
      id: 'acceptance',
      title: t('legal.terms.acceptanceTitle', '1. Acceptance of Terms'),
      body: t(
        'legal.terms.acceptance',
        'By accessing or using IdeaGo ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.',
      ),
    },
    {
      id: 'description',
      title: t('legal.terms.descriptionTitle', '2. Description of Service'),
      body: t(
        'legal.terms.description',
        'IdeaGo is an AI-powered competitor research platform. We aggregate publicly available information and generate analytical reports. Reports are generated by AI and may contain inaccuracies.',
      ),
    },
    {
      id: 'accounts',
      title: t('legal.terms.accountsTitle', '3. User Accounts'),
      body: t(
        'legal.terms.accounts',
        'You are responsible for maintaining the security of your account credentials. You must not share your account or use the Service for any unlawful purpose.',
      ),
    },
    {
      id: 'subscription',
      title: t('legal.terms.subscriptionTitle', '4. Subscriptions & Billing'),
      body: t(
        'legal.terms.subscription',
        'Paid plans are billed through Stripe. You can cancel at any time through your account settings. Refunds are handled per our refund policy.',
      ),
    },
    {
      id: 'ip',
      title: t('legal.terms.ipTitle', '5. Intellectual Property'),
      body: t(
        'legal.terms.ip',
        'Reports generated for you are yours to use. The Service, its code, and branding remain the property of IdeaGo.',
      ),
    },
    {
      id: 'disclaimer',
      title: t('legal.terms.disclaimerTitle', '6. Disclaimer'),
      body: t(
        'legal.terms.disclaimer',
        'The Service is provided "as is". We do not guarantee the accuracy, completeness, or timeliness of any information provided. Use reports at your own risk.',
      ),
    },
    {
      id: 'limitation',
      title: t('legal.terms.limitationTitle', '7. Limitation of Liability'),
      body: t(
        'legal.terms.limitation',
        'To the maximum extent permitted by law, IdeaGo shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.',
      ),
    },
    {
      id: 'changes',
      title: t('legal.terms.changesTitle', '8. Changes to Terms'),
      body: t(
        'legal.terms.changes',
        'We may update these terms from time to time. Continued use of the Service constitutes acceptance of the updated terms.',
      ),
    },
    {
      id: 'contact',
      title: t('legal.terms.contactTitle', '9. Contact'),
      body: t(
        'legal.terms.contact',
        'For questions about these terms, please contact us through the channels listed on our website.',
      ),
    },
  ]

  return (
    <div className="relative min-h-screen overflow-hidden bg-background px-4 pb-20 text-foreground">
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 opacity-[0.05]"
        style={{
          backgroundImage:
            'radial-gradient(circle at 1px 1px, var(--foreground) 1px, transparent 0), linear-gradient(135deg, color-mix(in oklab, var(--primary) 10%, transparent), transparent 38%)',
          backgroundSize: '28px 28px, 100% 100%',
        }}
      />
      <div className="absolute right-0 top-28 h-56 w-56 -translate-x-8 border-8 border-primary/20 bg-primary/10" aria-hidden="true" />
      <div className="absolute left-8 top-64 h-20 w-20 border-4 border-border bg-card shadow-lg" aria-hidden="true" />

      <article className="app-shell relative z-10 max-w-6xl">
        <header className="border-4 border-border bg-card shadow-xl">
          <div className="grid gap-8 p-6 md:grid-cols-[minmax(0,1.4fr)_280px] md:p-10">
            <div>
              <Link
                to="/"
                className="mb-6 inline-flex min-h-[44px] items-center gap-2 text-sm font-bold uppercase tracking-widest text-muted-foreground transition-colors hover:text-foreground"
              >
                <ArrowLeft className="h-4 w-4" aria-hidden="true" />
                {t('legal.backToHome', 'Back to Home')}
              </Link>

              <div className="mb-5 inline-flex items-center border-2 border-border bg-primary px-4 py-2 text-xs font-black uppercase tracking-[0.3em] text-primary-foreground shadow">
                {pageCopy.summaryLabel}
              </div>

              <h1 className="max-w-3xl text-[clamp(2.8rem,7vw,5.6rem)] leading-[0.9] text-foreground">
                {t('legal.termsTitle', 'Terms of Service')}
              </h1>

              <p className="mt-6 max-w-2xl border-l-8 border-primary pl-5 text-base font-medium leading-8 text-muted-foreground md:text-lg">
                {pageCopy.intro}
              </p>
            </div>

            <div className="flex flex-col gap-4 border-2 border-border bg-background p-5 shadow-md">
              <div>
                <p className="text-xs font-black uppercase tracking-[0.28em] text-muted-foreground">
                  {t('legal.lastUpdated', 'Last updated')}
                </p>
                <p className="mt-2 text-2xl font-black text-foreground">2026-03-27</p>
              </div>

              <div className="border-t-2 border-border pt-4">
                <p className="text-xs font-black uppercase tracking-[0.28em] text-muted-foreground">
                  {pageCopy.panelTitle}
                </p>
                <p className="mt-3 text-sm leading-7 text-muted-foreground">{pageCopy.panelBody}</p>
              </div>

              <div className="border-t-2 border-border pt-4">
                <p className="text-xs font-black uppercase tracking-[0.28em] text-muted-foreground">
                  {pageCopy.summaryLabel}
                </p>
                <p className="mt-3 text-sm font-bold leading-7 text-foreground">{pageCopy.summaryValue}</p>
              </div>
            </div>
          </div>
        </header>

        <div className="mt-10 grid gap-8 lg:grid-cols-[220px_minmax(0,1fr)] lg:items-start">
          <aside className="border-2 border-border bg-card p-5 shadow-md lg:sticky lg:top-32">
            <p className="mb-4 text-xs font-black uppercase tracking-[0.28em] text-muted-foreground">
              {pageCopy.navTitle}
            </p>
            <nav aria-label={pageCopy.navTitle} className="space-y-2">
              {sections.map(section => (
                <a
                  key={section.id}
                  href={`#${section.id}`}
                  className="group flex items-start justify-between gap-3 border-2 border-transparent px-3 py-3 text-sm font-bold leading-6 text-muted-foreground transition-all hover:border-border hover:bg-background hover:text-foreground"
                >
                  <span>{section.title}</span>
                  <ArrowRight className="mt-1 h-4 w-4 shrink-0 transition-transform group-hover:translate-x-1" aria-hidden="true" />
                </a>
              ))}
            </nav>
          </aside>

          <div className="space-y-5">
            {sections.map(section => (
              <section
                key={section.id}
                id={section.id}
                className="border-4 border-border bg-card p-6 shadow-lg transition-transform duration-200 hover:-translate-y-1 md:p-8"
              >
                <div className="mb-5 flex items-start gap-4">
                  <div className="flex h-12 w-12 shrink-0 items-center justify-center border-2 border-border bg-primary text-lg font-black text-primary-foreground shadow">
                    {section.title.split('.')[0]}
                  </div>
                  <div className="min-w-0">
                    <h2 className="text-[clamp(1.7rem,4vw,2.8rem)] leading-[1.02] text-foreground">{section.title}</h2>
                  </div>
                </div>
                <p className="max-w-4xl text-base leading-8 text-muted-foreground md:text-lg">{section.body}</p>
              </section>
            ))}

            <section className="border-4 border-border bg-primary px-6 py-7 text-primary-foreground shadow-xl md:px-8">
              <p className="text-xs font-black uppercase tracking-[0.28em] opacity-80">{pageCopy.noteTitle}</p>
              <p className="mt-3 max-w-4xl text-base font-bold leading-8 md:text-lg">{pageCopy.noteBody}</p>
            </section>
          </div>
        </div>
      </article>
    </div>
  )
}
