"""Research domain models.

竞品调研领域模型：Platform、RawResult、Intent、Competitor、SourceResult、ResearchReport。
"""

import hashlib
from datetime import datetime, timezone
from enum import Enum
from typing import Any, cast
from uuid import uuid4

from pydantic import Field, field_validator

from ideago.models.base import BaseModel, TimestampMixin


class Platform(str, Enum):
    """Supported data source platforms / 支持的数据源平台。"""

    GITHUB = "github"
    TAVILY = "tavily"
    HACKERNEWS = "hackernews"
    APPSTORE = "appstore"
    PRODUCT_HUNT = "producthunt"
    REDDIT = "reddit"
    GOOGLE_TRENDS = "google_trends"


class RawResult(BaseModel):
    """Single raw result from a data source / 数据源返回的单条原始结果。"""

    title: str = Field(description="Result title / 结果标题")
    description: str = Field(default="", description="Result description / 结果描述")
    url: str = Field(description="Source URL, mandatory / 来源链接（必填）")
    platform: Platform = Field(description="Source platform / 来源平台")
    raw_data: dict[str, Any] = Field(
        default_factory=dict,
        description="Raw API response preserved for debugging / 原始响应备份",
    )
    fetched_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Fetch timestamp / 抓取时间",
    )


class SearchQuery(BaseModel):
    """Platform-specific search queries / 平台定制搜索词。"""

    platform: Platform = Field(description="Target platform / 目标平台")
    queries: list[str] = Field(
        min_length=1,
        description="Search query strings tailored for this platform",
    )


class Intent(BaseModel):
    """Parsed user intent with per-platform search queries / 解析后的用户意图。"""

    keywords_en: list[str] = Field(
        min_length=1,
        description="English keywords extracted from user input",
    )
    keywords_zh: list[str] = Field(
        default_factory=list,
        description="Chinese keywords if applicable",
    )
    exact_entities: list[str] = Field(
        default_factory=list,
        description="Exact multi-word entities or product names preserved from input",
    )
    comparison_anchors: list[str] = Field(
        default_factory=list,
        description="Explicit comparison anchors such as similar products or incumbents",
    )
    search_goal: str = Field(
        default="",
        description="Normalized research goal such as finding direct competitors",
    )
    app_type: str = Field(
        description="App form: web / mobile / browser-extension / cli / api / desktop",
    )
    target_scenario: str = Field(
        description="One-sentence target scenario description",
    )
    output_language: str = Field(
        default="en",
        description="Target language for generated report content: zh or en",
    )
    search_queries: list[SearchQuery] = Field(
        default_factory=list,
        description="Per-platform tailored search queries (legacy, now generated by QueryBuilder)",
    )
    cache_key: str = Field(
        default="",
        description="Normalized cache key derived from sorted keywords + app_type",
    )

    def compute_cache_key(self) -> str:
        """Generate a deterministic cache key from keywords + app_type.

        Same keywords in different order produce the same key.
        """
        normalized = sorted(k.lower().strip() for k in self.keywords_en)
        exact_entities = sorted(
            entity.lower().strip() for entity in self.exact_entities
        )
        comparison_anchors = sorted(
            anchor.lower().strip() for anchor in self.comparison_anchors
        )
        raw = (
            f"{self.app_type.lower()}::{'|'.join(normalized)}"
            f"::{'|'.join(exact_entities)}::{'|'.join(comparison_anchors)}"
        )
        return hashlib.sha256(raw.encode()).hexdigest()[:16]


class RelevanceKind(str, Enum):
    """Typed competitor relevance relative to the user's anchored ecosystem."""

    DIRECT = "direct"
    ADJACENT = "adjacent"


class QueryFamily(str, Enum):
    """Planning-stage query families for intent-aware search expansion."""

    DIRECT_COMPETITOR = "direct_competitor"
    ADJACENT_ANALOGY = "adjacent_analogy"
    WORKFLOW_INTERFACE = "workflow_interface"
    PAIN_DISCOVERY = "pain_discovery"
    COMMERCIAL_DISCOVERY = "commercial_discovery"
    DISCUSSION_DISCOVERY = "discussion_discovery"


class QueryRewrite(BaseModel):
    """One rewritten query generated during planning."""

    query: str = Field(description="One concrete rewritten query string")
    family: QueryFamily = Field(description="Planning family for this query")
    purpose: str = Field(description="Short rationale for why this query exists")


class QueryGroup(BaseModel):
    """A family of rewritten queries anchored to explicit entities."""

    family: QueryFamily = Field(description="Planning family represented by this group")
    anchor_terms: list[str] = Field(
        default_factory=list,
        description="Exact entities that must remain visible in rewrites",
    )
    comparison_anchors: list[str] = Field(
        default_factory=list,
        description="Comparison products or analogues that shape rewrites",
    )
    rewritten_queries: list[QueryRewrite] = Field(
        default_factory=list,
        description="Concrete rewrites generated for this group",
    )


class QueryPlan(BaseModel):
    """Structured query-planning output before platform adaptation."""

    query_groups: list[QueryGroup] = Field(
        default_factory=list,
        description="Planned query groups for downstream platform adaptation",
    )


class Competitor(BaseModel):
    """A competitor product identified during research / 调研中发现的竞品。"""

    name: str = Field(description="Product or project name / 产品名称")
    links: list[str] = Field(
        min_length=1,
        description="URLs — at least 1 required, no link = not recorded",
    )
    one_liner: str = Field(description="One-sentence positioning / 一句话定位")
    features: list[str] = Field(
        default_factory=list,
        description="Key features / 主要功能",
    )
    pricing: str | None = Field(
        default=None,
        description="Pricing info if available / 定价信息",
    )
    strengths: list[str] = Field(default_factory=list)
    weaknesses: list[str] = Field(default_factory=list)
    relevance_score: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="0-1 relevance score, higher = more relevant",
    )
    relevance_kind: RelevanceKind = Field(
        default=RelevanceKind.DIRECT,
        description="Whether this product is a direct competitor or adjacent analogue",
    )
    source_platforms: list[Platform] = Field(
        description="Platforms where this competitor was found",
    )
    source_urls: list[str] = Field(
        description="Original pages where info was extracted from",
    )


class RecommendationType(str, Enum):
    """Structured recommendation type / 结构化推荐类型。"""

    GO = "go"
    CAUTION = "caution"
    NO_GO = "no_go"


class EvidenceCategory(str, Enum):
    """Evidence category used in decision-first report sections."""

    COMPETITOR = "competitor"
    PAIN = "pain"
    COMMERCIAL = "commercial"
    MIGRATION = "migration"
    WHITESPACE = "whitespace"
    MARKET = "market"


class SourceStatus(str, Enum):
    """Status of a data source query / 数据源查询状态。"""

    OK = "ok"
    FAILED = "failed"
    CACHED = "cached"
    TIMEOUT = "timeout"
    DEGRADED = "degraded"


class SourceResult(BaseModel):
    """Result from one data source including status / 单个数据源结果（含状态）。"""

    platform: Platform
    status: SourceStatus
    raw_count: int = Field(
        default=0,
        description="Number of raw results fetched / 抓取到的原始结果数",
    )
    competitors: list[Competitor] = Field(default_factory=list)
    error_msg: str | None = Field(default=None)
    duration_ms: int = Field(
        default=0,
        description="Time taken for this source in milliseconds",
    )


class PainSignal(BaseModel):
    """Signal describing recurring user pain and severity."""

    theme: str = Field(description="Pain theme label")
    summary: str = Field(
        default="",
        description="Short summary of the pain context",
    )
    intensity: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Pain intensity score (0-1)",
    )
    frequency: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="How frequently this pain appears across evidence (0-1)",
    )
    evidence_urls: list[str] = Field(
        default_factory=list,
        description="Supporting evidence URLs",
    )
    source_platforms: list[Platform] = Field(
        default_factory=list,
        description="Platforms where the pain signal was observed",
    )


class CommercialSignal(BaseModel):
    """Signal indicating monetizable demand or willingness to pay."""

    theme: str = Field(description="Commercial intent theme label")
    summary: str = Field(
        default="",
        description="Short summary of demand/commercial context",
    )
    intent_strength: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Commercial intent strength score (0-1)",
    )
    monetization_hint: str = Field(
        default="",
        description="Potential monetization angle",
    )
    evidence_urls: list[str] = Field(
        default_factory=list,
        description="Supporting evidence URLs",
    )
    source_platforms: list[Platform] = Field(
        default_factory=list,
        description="Platforms where the commercial signal was observed",
    )


class WhitespaceOpportunity(BaseModel):
    """Potential underserved wedge inferred from evidence."""

    title: str = Field(description="Opportunity title")
    description: str = Field(
        default="",
        description="Opportunity details and rationale",
    )
    target_segment: str = Field(
        default="",
        description="Target user segment for this wedge",
    )
    wedge: str = Field(
        default="",
        description="Concrete entry wedge suggestion",
    )
    potential_score: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Potential value score for this opportunity (0-1)",
    )
    confidence: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Confidence in this opportunity (0-1)",
    )
    supporting_evidence: list[str] = Field(
        default_factory=list,
        description="Evidence URLs or IDs supporting the opportunity",
    )


class OpportunityScoreBreakdown(BaseModel):
    """Deterministic opportunity score components."""

    pain_intensity: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Weighted pain intensity component (0-1)",
    )
    solution_gap: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Weighted solution gap component (0-1)",
    )
    commercial_intent: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Weighted commercial intent component (0-1)",
    )
    freshness: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Weighted freshness component (0-1)",
    )
    competition_density: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Weighted competition density component (0-1)",
    )
    score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Final opportunity score (0-1)",
    )


class ConfidenceMetrics(BaseModel):
    """Confidence metrics for report quality and source reliability."""

    sample_size: int = Field(default=0, ge=0, description="Evidence sample size")
    source_coverage: int = Field(
        default=0,
        ge=0,
        description="Number of sources that returned usable results",
    )
    source_success_rate: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Effective source success rate after degraded-source discounting",
    )
    source_diversity: int = Field(
        default=0,
        ge=0,
        description="Distinct supporting source platforms represented in evidence",
    )
    evidence_density: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Density of usable evidence and corroborating signals (0-1)",
    )
    recency_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Freshness score derived from evidence timestamps (0-1)",
    )
    degradation_penalty: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Penalty from degraded, failed, or timed-out sources (0-1)",
    )
    contradiction_penalty: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Penalty from explicit uncertainty or conflicting evidence (0-1)",
    )
    reasons: list[str] = Field(
        default_factory=list,
        description="Human-readable confidence drivers and penalties",
    )
    freshness_hint: str = Field(
        default="Generated moments ago",
        description="Relative report freshness text for UI display",
    )
    score: int = Field(default=0, ge=0, le=100, description="Overall confidence 0-100")


class EvidenceItem(BaseModel):
    """Single evidence item attached to report conclusion."""

    title: str = Field(default="", description="Evidence title")
    url: str = Field(default="", description="Evidence URL")
    platform: Platform | None = Field(
        default=None,
        description="Source platform enum, optional for legacy payloads",
    )
    snippet: str = Field(default="", description="Evidence snippet")
    category: EvidenceCategory = Field(
        default=EvidenceCategory.MARKET,
        description="Evidence category",
    )
    freshness_hint: str = Field(
        default="",
        description="Optional freshness hint for this evidence",
    )
    matched_query: str = Field(
        default="",
        description="Query string that matched this evidence",
    )
    query_family: str = Field(
        default="",
        description="Research intent family that produced this evidence",
    )

    @field_validator("platform", mode="before")
    @classmethod
    def _normalize_platform(cls, value: object) -> Platform | None:
        """Allow legacy empty-string platform payloads without failing validation."""
        if value in ("", None):
            return None
        if isinstance(value, Platform):
            return value
        if isinstance(value, str):
            return Platform(value)
        # Keep unknown payloads on the normal Pydantic validation path so callers
        # consistently receive ValidationError instead of raw exceptions.
        return cast(Platform | None, value)


class EvidenceSummary(BaseModel):
    """Evidence summary section for transparency."""

    top_evidence: list[str] = Field(
        default_factory=list,
        description="Human-readable top evidence highlights",
    )
    evidence_items: list[EvidenceItem] = Field(
        default_factory=list,
        description="Structured evidence items used by report sections",
    )
    category_counts: dict[str, int] = Field(
        default_factory=dict,
        description="Evidence counts grouped by category key",
    )
    source_platforms: list[Platform] = Field(
        default_factory=list,
        description="Distinct source platforms represented in evidence items",
    )
    freshness_distribution: dict[str, int] = Field(
        default_factory=dict,
        description="Evidence freshness counts grouped into summary buckets",
    )
    degraded_sources: list[Platform] = Field(
        default_factory=list,
        description="Sources that were degraded, failed, or timed out during retrieval",
    )
    uncertainty_notes: list[str] = Field(
        default_factory=list,
        description="Explicit uncertainty notes for weak/contradicting evidence",
    )


class CostBreakdown(BaseModel):
    """Cost and latency telemetry of one report run."""

    llm_calls: int = Field(default=0, ge=0)
    llm_retries: int = Field(default=0, ge=0)
    endpoint_failovers: int = Field(default=0, ge=0)
    source_calls: int = Field(default=0, ge=0)
    pipeline_latency_ms: int = Field(default=0, ge=0)
    tokens_prompt: int = Field(default=0, ge=0)
    tokens_completion: int = Field(default=0, ge=0)


class LlmFaultToleranceMeta(BaseModel):
    """LLM fault-tolerance metadata for this report."""

    fallback_used: bool = Field(default=False)
    endpoints_tried: list[str] = Field(default_factory=list)
    last_error_class: str = Field(default="")


class ReportMeta(BaseModel):
    """Additional report metadata for observability and debugging."""

    llm_fault_tolerance: LlmFaultToleranceMeta = Field(
        default_factory=LlmFaultToleranceMeta
    )
    quality_warnings: list[str] = Field(
        default_factory=list,
        description="Quality guardrail notes for recommendation reliability.",
    )


class ResearchReport(TimestampMixin):
    """Complete research report / 完整调研报告。"""

    id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique report ID / 报告唯一标识",
    )
    query: str = Field(
        description="User's original natural language input / 用户原始输入"
    )
    intent: Intent
    source_results: list[SourceResult] = Field(default_factory=list)
    competitors: list[Competitor] = Field(
        default_factory=list,
        description="Globally deduplicated competitor list / 全局去重竞品列表",
    )
    pain_signals: list[PainSignal] = Field(
        default_factory=list,
        description="Aggregated user pain signals extracted from evidence",
    )
    commercial_signals: list[CommercialSignal] = Field(
        default_factory=list,
        description="Aggregated commercial intent signals from evidence",
    )
    whitespace_opportunities: list[WhitespaceOpportunity] = Field(
        default_factory=list,
        description="Whitespace opportunities and entry wedges",
    )
    opportunity_score: OpportunityScoreBreakdown = Field(
        default_factory=OpportunityScoreBreakdown,
        description="Deterministic opportunity score breakdown",
    )
    market_summary: str = Field(
        default="",
        description="LLM-generated market analysis / 市场分析摘要",
    )
    go_no_go: str = Field(
        default="",
        description="Go/No-Go recommendation with reasoning / 推荐建议",
    )
    recommendation_type: RecommendationType = Field(
        default=RecommendationType.GO,
        description="Structured recommendation: go / caution / no_go",
    )
    differentiation_angles: list[str] = Field(
        default_factory=list,
        description="Suggested differentiation points / 差异化切入点",
    )
    confidence: ConfidenceMetrics = Field(default_factory=ConfidenceMetrics)
    evidence_summary: EvidenceSummary = Field(default_factory=EvidenceSummary)
    cost_breakdown: CostBreakdown = Field(default_factory=CostBreakdown)
    report_meta: ReportMeta = Field(default_factory=ReportMeta)
